# Generated by Django 6.0.6 on 2026-06-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='subcategory',
            new_name='category',
        ),
    ]
