# Generated by Django 6.0.6 on 2026-06-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_subcategory_record_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='category',
            new_name='subcategory',
        ),
    ]
