# Generated by Django 6.0.6 on 2026-06-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory_user'),
        ('records', '0003_rename_category_record_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.maincategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory'),
        ),
    ]
